# Generated by Django 3.2.7 on 2021-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('measurement', models.CharField(max_length=5, unique=True)),
                ('provider', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
