# Generated by Django 3.2.7 on 2021-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
